[Global]
Key = "containers/hidden_server/id_client.pem"
Certificate = "containers/hidden_server/id_client.cert"
CAFiles = ["containers/CAFiles/intermediate.cert", "containers/CAFiles/root.cert"]

[[Hosts]]
Patterns = ["127.0.0.1"]
ServerName = "hidden.com"
Port = 5555
ServerKEMKeyPath = "containers/hidden_server/kem_hop.pub"