[Global]
Key = "./artifact/hop-configs/id_hop.pem"
Certificate = "./artifact/hop-configs/sg/id_hop.cert"
CAFiles = ["./artifact/hop-configs/CAFiles/intermediate.cert", "./artifact/hop-configs/CAFiles/root.cert"]

[[Hosts]]
Patterns = ["127.0.0.1"]
ServerName = "127.0.0.1"
Port = 77

ServerKEMKeyPath = "./artifact/hop-configs/kem_hop.pub"