ListenAddress = ":77"

Key = "/etc/hopd/id_hop.pem"
Certificate = "/etc/hopd/id_hop.cert"
CAFiles = [ "/etc/hopd/intermediate.cert" , "/etc/hopd/root.cert" ]

InsecureSkipVerify = true

Users = ["acme_user"]
