[Global]
IsDelegate = true
CAFiles = ["/home/user/.hop/intermediate.cert", "/home/user/.hop/root.cert"]


[[Hosts]]
Patterns = ["172.17.0.2"]
ServerName = "target.com"

[[Hosts]]
Patterns = ["172.17.0.4"]
ServerName = "third.com"
